export const {
    FAIRY_IN_HORIZONTAL_LINE,
    FAIRY_IN_VERTICAL_LINE,
    LEFT_PADDING,
    TOP_PADDING,
    FAIRY_RADIUS,
} = {
    FAIRY_IN_HORIZONTAL_LINE: 5,
    FAIRY_IN_VERTICAL_LINE: 3,
    LEFT_PADDING: 5,
    TOP_PADDING: 15,
    FAIRY_RADIUS: 7.5
};