export const BUTTON_COLOR_VARIANTS = {
    light: {
        bg: 'var(--basis-contrast)',
        color: 'var(--basis)',
        bgHover: 'var(--secondary-200)',
        colorHover: 'var(--main-600)',
        bgFocus: 'var(--secondary-200)',
        colorFocus: 'var(--basis)',
        borderFocus: 'var(--secondary-400)',
        bgActive: 'var(--basis-contrast)',
        colorActive: 'var(--secondary-800)',
    },
    dark: {
        bg: 'var(--main-700)',
        color: 'var(--basis-contrast)',
        bgHover: 'var(--main-800)',
        colorHover: 'var(--basis-contrast)',
        bgFocus: 'var(--main-700)',
        colorFocus: 'var(--basis-contrast)',
        borderFocus: 'var(--secondary-800)',
        bgActive: 'var(--main-900)',
        colorActive: 'var(--secondary-400)',
    },
    ghostLight: {
        bg: 'none',
        color: 'var(--main-600)',
        bgHover: 'none',
        colorHover: 'var(--main-700)',
        bgFocus: 'none',
        colorFocus: 'var(--main-800)',
        borderFocus: 'transparent',
        bgActive: 'none',
        colorActive: 'var(--basis)',
    },
    ghostDark: {
        bg: 'none',
        color: 'var(--secondary-400)',
        bgHover: 'none',
        colorHover: 'var(--secondary-100',
        bgFocus: 'none',
        colorFocus: 'var(--secondary-400)',
        borderFocus: 'transparent',
        bgActive: 'none',
        colorActive: 'var(--basis-contrast)',
    },
} as const;

export const BUTTON_SIZES = {
    M: {
        height: '40px',
        paddingVertical: '10px',
        paddingHorizontal: '16px',
        gap: '6px',
        borderRadius: '12px',
    },
    S: {
        height: '32px',
        paddingVertical: '8px',
        paddingHorizontal: '16px',
        gap: '6px',
        borderRadius: '8px',
    },
    XS: {
        height: '24px',
        paddingVertical: '6px',
        paddingHorizontal: '10px',
        gap: '4px',
        borderRadius: '6px',
    },
} as const;
